// <auto-generated />
using System;
using Hardware;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hardware.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20260514115807_RestrictOnDelete")]
    partial class RestrictOnDelete
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Hardware.Models.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("Hardware.Models.Cabinet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BuildingId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.ToTable("Cabinets");
                });

            modelBuilder.Entity("Hardware.Models.Complect", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CabinetId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CabinetId");

                    b.ToTable("Complects");
                });

            modelBuilder.Entity("Hardware.Models.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ComplectId")
                        .HasColumnType("int");

                    b.Property<int>("DeviceNameId")
                        .HasColumnType("int");

                    b.Property<int>("DeviceProviderId")
                        .HasColumnType("int");

                    b.Property<string>("Inventory")
                        .HasColumnType("longtext");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<string>("Serial")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ComplectId");

                    b.HasIndex("DeviceNameId");

                    b.HasIndex("DeviceProviderId");

                    b.HasIndex("Serial")
                        .IsUnique();

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("Hardware.Models.DeviceName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeviceTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DeviceTypeId");

                    b.ToTable("DeviceNames");
                });

            modelBuilder.Entity("Hardware.Models.DeviceProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("DeviceProviders");
                });

            modelBuilder.Entity("Hardware.Models.DeviceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("DeviceTypes");
                });

            modelBuilder.Entity("Hardware.Models.History", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("After")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Before")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("History");
                });

            modelBuilder.Entity("Hardware.Models.Cabinet", b =>
                {
                    b.HasOne("Hardware.Models.Building", "Building")
                        .WithMany("Cabinets")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("Hardware.Models.Complect", b =>
                {
                    b.HasOne("Hardware.Models.Cabinet", "Cabinet")
                        .WithMany("Complects")
                        .HasForeignKey("CabinetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cabinet");
                });

            modelBuilder.Entity("Hardware.Models.Device", b =>
                {
                    b.HasOne("Hardware.Models.Complect", "Complect")
                        .WithMany("Devices")
                        .HasForeignKey("ComplectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hardware.Models.DeviceName", "DeviceName")
                        .WithMany("Devices")
                        .HasForeignKey("DeviceNameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hardware.Models.DeviceProvider", "DeviceProvider")
                        .WithMany("Devices")
                        .HasForeignKey("DeviceProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Complect");

                    b.Navigation("DeviceName");

                    b.Navigation("DeviceProvider");
                });

            modelBuilder.Entity("Hardware.Models.DeviceName", b =>
                {
                    b.HasOne("Hardware.Models.DeviceType", "DeviceType")
                        .WithMany("DeviceNames")
                        .HasForeignKey("DeviceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeviceType");
                });

            modelBuilder.Entity("Hardware.Models.Building", b =>
                {
                    b.Navigation("Cabinets");
                });

            modelBuilder.Entity("Hardware.Models.Cabinet", b =>
                {
                    b.Navigation("Complects");
                });

            modelBuilder.Entity("Hardware.Models.Complect", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("Hardware.Models.DeviceName", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("Hardware.Models.DeviceProvider", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("Hardware.Models.DeviceType", b =>
                {
                    b.Navigation("DeviceNames");
                });
#pragma warning restore 612, 618
        }
    }
}
